# Generated by Django 4.2.4 on 2023-08-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='product_og_price3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='manwomen',
            name='product_og_price1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='panttrouser',
            name='product_og_price2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='product_image3',
            field=models.ImageField(null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='product_price3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='manwomen',
            name='product_image1',
            field=models.ImageField(null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='manwomen',
            name='product_price1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='panttrouser',
            name='product_image2',
            field=models.ImageField(null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='panttrouser',
            name='product_price2',
            field=models.IntegerField(null=True),
        ),
    ]
