# Generated by Django 4.2.4 on 2023-08-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_clothing_product_og_price3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopgrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image4', models.ImageField(null=True, upload_to='images')),
                ('product_name4', models.CharField(max_length=50)),
                ('product_price4', models.IntegerField(null=True)),
                ('product_og_price4', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clothing',
            name='product_image3',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='manwomen',
            name='product_image1',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='panttrouser',
            name='product_image2',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
