# Generated by Django 4.2.4 on 2023-08-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_shopgrid_alter_clothing_product_image3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='relatedproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image5', models.ImageField(null=True, upload_to='images')),
                ('product_name5', models.CharField(max_length=50)),
                ('product_price5', models.IntegerField(null=True)),
                ('product_og_price5', models.IntegerField(null=True)),
            ],
        ),
    ]
