# Generated by Django 4.2.4 on 2023-08-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_relatedproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image6', models.ImageField(null=True, upload_to='images')),
                ('product_name6', models.CharField(max_length=50)),
                ('product_price6', models.IntegerField(null=True)),
                ('product_og_price6', models.IntegerField(null=True)),
            ],
        ),
    ]
