# Generated by Django 4.2.4 on 2023-08-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name6', models.CharField(max_length=50)),
                ('product_price6', models.IntegerField(null=True)),
                ('product_og_price6', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_name6',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_og_price6',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_price6',
        ),
    ]
