# Generated by Django 4.2.4 on 2023-08-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price_offer',
            field=models.IntegerField(),
        ),
    ]
