# Generated by Django 4.2.4 on 2023-08-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_item_item_price_alter_item_item_price_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clothing',
        ),
        migrations.DeleteModel(
            name='manwomen',
        ),
        migrations.DeleteModel(
            name='panttrouser',
        ),
        migrations.DeleteModel(
            name='price',
        ),
        migrations.DeleteModel(
            name='products',
        ),
        migrations.DeleteModel(
            name='relatedproducts',
        ),
        migrations.DeleteModel(
            name='shopgrid',
        ),
    ]
